import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Search, Download, FileCheck2, FlaskConical, ShieldCheck } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { TEST_REPORTS, type TestReport } from "@/data/testReports";

export const Route = createFileRoute("/testing")({
  head: () => ({
    meta: [
      { title: "Every Batch. Independently Tested. Fully Transparent." },
      {
        name: "description",
        content:
          "Search Ellivion Healthcare batch test reports by batch number. Download lab-verified quality reports as PDF.",
      },
      { property: "og:title", content: "Every Batch. Independently Tested. Fully Transparent." },
      {
        property: "og:description",
        content:
          "Transparent lab testing. Enter a batch number to view and download the full quality report.",
      },
    ],
  }),
  component: TestingPage,
});

function generatePdf(report: TestReport) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(15, 27, 61);
  doc.rect(0, 0, pageWidth, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("ELLIVION HEALTHCARE PVT. LTD.", 40, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Certificate of Analysis — Batch Test Report", 40, 62);
  doc.setFontSize(9);
  doc.text("Tested. Trusted. Wellness you can verify.", 40, 78);

  // Body
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(11);
  let y = 120;

  const meta: Array<[string, string]> = [
    ["Report Number", report.reportNumber],
    ["Batch Number", report.batchNumber],
    ["Product Name", report.productName],
    ["Category", report.category],
    ["Manufacturing Date", report.manufacturingDate],
    ["Expiry Date", report.expiryDate],
    ["Date of Testing", report.testDate],
    ["Testing Laboratory", report.labName],
  ];

  doc.setFont("helvetica", "bold");
  doc.text("Product & Batch Information", 40, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  meta.forEach(([k, v]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${k}:`, 40, y);
    doc.setFont("helvetica", "normal");
    doc.text(v, 180, y);
    y += 16;
  });

  y += 10;
  autoTable(doc, {
    startY: y,
    head: [["Parameter", "Specification", "Observed Result", "Status"]],
    body: report.parameters.map((p) => [p.parameter, p.specification, p.result, p.status]),
    headStyles: { fillColor: [246, 34, 147], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 6 },
    alternateRowStyles: { fillColor: [255, 235, 245] },
    margin: { left: 40, right: 40 },
  });

  const afterTableY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 24;
  doc.setFont("helvetica", "bold");
  doc.text("Conclusion", 40, afterTableY);
  doc.setFont("helvetica", "normal");
  const lines = doc.splitTextToSize(report.conclusion, pageWidth - 80);
  doc.text(lines, 40, afterTableY + 16);

  // Signature
  const sigY = afterTableY + 16 + lines.length * 14 + 60;
  doc.line(40, sigY, 220, sigY);
  doc.text("Authorised Signatory", 40, sigY + 14);
  doc.text("Quality Assurance Department", 40, sigY + 28);

  doc.line(pageWidth - 220, sigY, pageWidth - 40, sigY);
  doc.text("Ellivion Healthcare Pvt. Ltd.", pageWidth - 220, sigY + 14);
  doc.text("Mumbai, India", pageWidth - 220, sigY + 28);

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "This report relates only to the batch tested. Generated by Ellivion Healthcare digital QA system.",
    40,
    doc.internal.pageSize.getHeight() - 30,
  );

  doc.save(`Ellivion-Report-${report.batchNumber}.pdf`);
}

function TestingPage() {
  const [query, setQuery] = useState("");
  const [searched, setSearched] = useState(false);

  const result = useMemo<TestReport | null>(() => {
    const q = query.trim().toLowerCase();
    if (!q) return null;
    return TEST_REPORTS.find((r) => r.batchNumber.toLowerCase() === q) ?? null;
  }, [query]);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    setSearched(true);
  };

  return (
    <div className="bg-background">
      {/* Hero */}
      <section className="relative bg-navy text-white py-20 md:py-28 overflow-hidden">
        <div className="absolute inset-0 opacity-20 bg-gradient-to-br from-pink/40 via-transparent to-pink/10" />
        <div className="relative mx-auto max-w-7xl px-6 lg:px-10 text-center">
          <p className="text-pink uppercase tracking-[0.3em] text-xs font-semibold">Quality you can verify</p>
          <h1 className="font-display text-4xl md:text-6xl mt-4 text-white">Every Batch. Independently Tested. Fully Transparent.
</h1>
          <p className="mt-5 text-white/80 max-w-2xl mx-auto">
         Every Ellivion product undergoes third-party laboratory testing to verify purity, potency, and safety. Enter your batch number below to access the Certificate of Analysis (COA) and view the quality standards behind your purchase.
          </p>
        </div>
      </section>

      {/* Search */}
      <section className="mx-auto max-w-3xl px-6 lg:px-10 -mt-12 relative z-10">
        <form
          onSubmit={handleSearch}
          className="bg-white border border-pink/20 shadow-xl rounded-2xl p-4 md:p-6 flex flex-col sm:flex-row gap-3"
        >
          <div className="flex items-center gap-3 flex-1 bg-secondary/40 rounded-xl px-4">
            <Search className="text-navy/60" size={20} />
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Enter batch number e.g. ELV-ASH-2026-001"
              className="w-full bg-transparent py-3 text-navy placeholder:text-navy/40 focus:outline-none"
            />
          </div>
          <button
            type="submit"
            className="btn-vibrant px-6 py-3 rounded-xl font-medium text-sm whitespace-nowrap"
          >
            Search report
          </button>
        </form>
        <p className="text-xs text-muted-foreground mt-3 text-center">
         Every production batch is tested by independent accredited laboratories to verify purity, potency, and safety before release.
:{" "}
          {TEST_REPORTS.map((r, i) => (
            <span key={r.batchNumber}>
              <button
                type="button"
                onClick={() => {
                  setQuery(r.batchNumber);
                  setSearched(true);
                }}
                className="text-pink hover:underline"
              >
                {r.batchNumber}
              </button>
              {i < TEST_REPORTS.length - 1 ? " · " : ""}
            </span>
          ))}
        </p>
      </section>

      {/* Result */}
      <section className="mx-auto max-w-5xl px-6 lg:px-10 py-16">
        {searched && !result && (
          <div className="text-center border border-dashed border-pink/30 rounded-2xl p-12">
            <FlaskConical className="mx-auto text-pink mb-4" size={40} />
            <h3 className="font-display text-2xl text-navy">No report found</h3>
            <p className="text-muted-foreground mt-2">
              We couldn't find a published report for that batch number. Please double-check the
              number printed on your product pack.
            </p>
          </div>
        )}

        {result && (
          <div className="rounded-2xl border border-pink/15 bg-white shadow-sm overflow-hidden animate-fade-up">
            <div className="bg-navy text-white px-6 md:px-10 py-6 flex flex-col md:flex-row md:items-center md:justify-between gap-4">
              <div>
                <p className="text-pink uppercase text-xs tracking-[0.25em] font-semibold">
                  Certificate of Analysis
                </p>
                <h2 className="font-display text-2xl md:text-3xl mt-1">{result.productName}</h2>
                <p className="text-white/70 text-sm mt-1">Batch: {result.batchNumber}</p>
              </div>
              <button
                onClick={() => generatePdf(result)}
                className="inline-flex items-center gap-2 bg-pink text-white px-5 py-3 rounded-xl text-sm font-medium hover:bg-pink/90 transition-colors"
              >
                <Download size={18} /> Download PDF
              </button>
            </div>

            <div className="grid sm:grid-cols-2 gap-x-8 gap-y-3 p-6 md:p-10 text-sm">
              <Detail label="Report Number" value={result.reportNumber} />
              <Detail label="Category" value={result.category} />
              <Detail label="Manufacturing Date" value={result.manufacturingDate} />
              <Detail label="Expiry Date" value={result.expiryDate} />
              <Detail label="Date of Testing" value={result.testDate} />
              <Detail label="Testing Lab" value={result.labName} />
            </div>

            <div className="px-6 md:px-10 pb-8">
              <h3 className="font-display text-xl text-navy mb-4">Test parameters</h3>
              <div className="overflow-x-auto rounded-xl border border-border">
                <table className="w-full text-sm">
                  <thead className="bg-secondary/50 text-navy">
                    <tr>
                      <th className="text-left px-4 py-3 font-semibold">Parameter</th>
                      <th className="text-left px-4 py-3 font-semibold">Specification</th>
                      <th className="text-left px-4 py-3 font-semibold">Observed Result</th>
                      <th className="text-left px-4 py-3 font-semibold">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {result.parameters.map((p) => (
                      <tr key={p.parameter} className="border-t border-border">
                        <td className="px-4 py-3 text-navy">{p.parameter}</td>
                        <td className="px-4 py-3 text-muted-foreground">{p.specification}</td>
                        <td className="px-4 py-3">{p.result}</td>
                        <td className="px-4 py-3">
                          <span
                            className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium ${
                              p.status === "Pass"
                                ? "bg-green-100 text-green-700"
                                : "bg-red-100 text-red-700"
                            }`}
                          >
                            <FileCheck2 size={12} /> {p.status}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="mt-6 flex gap-3 items-start bg-secondary/40 rounded-xl p-4">
                <ShieldCheck className="text-pink shrink-0 mt-0.5" size={20} />
                <p className="text-sm text-navy/80">{result.conclusion}</p>
              </div>
            </div>
          </div>
        )}

        {!searched && (
          <div className="grid md:grid-cols-3 gap-6">
            {[
              { icon: FlaskConical, title: "Third-Party Verified", text: "Every production batch is tested by independent accredited laboratories to verify purity, potency, and safety before release." },
              { icon: ShieldCheck, title: "Regulatory Compliance", text: "Testing is conducted in accordance with applicable quality standards and specifications to help ensure product consistency and integrity." },
              { icon: FileCheck2, title: "Complete Transparency", text: "Access batch-specific Certificates of Analysis and review the testing results for the product you purchased." },
            ].map(({ icon: Icon, title, text }) => (
              <div key={title} className="rounded-2xl border border-pink/15 p-6 bg-white">
                <Icon className="text-pink" size={26} />
                <h3 className="font-display text-xl text-navy mt-3">{title}</h3>
                <p className="text-sm text-muted-foreground mt-2">{text}</p>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}

function Detail({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p>
      <p className="text-navy font-medium mt-0.5">{value}</p>
    </div>
  );
}
